# Generated by Django 3.2 on 2021-05-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_library', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='country',
            field=models.CharField(default='None', max_length=25),
            preserve_default=False,
        ),
    ]
