# Generated by Django 3.2 on 2021-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_library', '0003_userinformation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='loginSessionHash',
            field=models.CharField(default='##########', max_length=10),
        ),
    ]
